FROM node:20-slim
WORKDIR /app
COPY discord-bot/package*.json ./
RUN npm install --include=dev
COPY discord-bot/tsconfig.json ./
COPY discord-bot/src ./src
RUN npm run build
CMD ["node", "dist/bot.js"]
